name: Java

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: "Edit config"
        run: git config --global user.email "sofiburiynova@yandex.ru" &&  git config --global user.name "Sophia Buriynova"
      - name: "Version patch"
        run: nmp version 0.1.$GITHUB_RUN_ID


      - name: Build
        run: mvn --batch-mode -DskipTests package
      - name: Test
        run: mvn --batch-mode test

      - name: "Telegram Notification"
        uses: "appleboy/telegran-actiongnaster"
        with:
         to: ${{ secrets. TELEGRAM_CHAT ID }}
         token: ${{secrets.TELEGRAM_TOKEN}}
         args: New 0.1.${{ github.run_id }} version publish

